/* SPDX-License-Identifier: LicenseRef-FNCL-1.1
 * Copyright (c) 2026 Cpt_Kirk
 */
#include "ui/fonts/mdi_font_registry.h"

#include <string.h>


static const mdi_icon_entry_t s_mdi_icons[] = {
    {
        "mdi:power",
        "Power",
        0xF0425U
    },
    {
        "mdi:timer-outline",
        "Timer outline",
        0xF051BU
    },
};


#ifndef APP_HAVE_MDI_ICON_FONT
#define APP_HAVE_MDI_ICON_FONT 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT
#define APP_HAVE_MDI_TOP50_FONT 0
#endif

#ifndef APP_HAVE_MDI_STANDARD_FONT
#define APP_HAVE_MDI_STANDARD_FONT 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT_72
#define APP_HAVE_MDI_TOP50_FONT_72 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT_56
#define APP_HAVE_MDI_TOP50_FONT_56 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT_42
#define APP_HAVE_MDI_TOP50_FONT_42 0
#endif

#ifndef APP_HAVE_MDI_TOP50_FONT_LEGACY
#define APP_HAVE_MDI_TOP50_FONT_LEGACY 0
#endif

#ifndef APP_HAVE_MDI_WEATHER_FONT_20
#define APP_HAVE_MDI_WEATHER_FONT_20 0
#endif


#if APP_HAVE_MDI_ICON_FONT

/* Generated by LVGL Font Converter.
 * The declared names must match the converter output.
 */

#if APP_HAVE_MDI_TOP50_FONT

#if APP_HAVE_MDI_TOP50_FONT_56
LV_FONT_DECLARE(mditop50icons56);
#endif

#if APP_HAVE_MDI_TOP50_FONT_42
LV_FONT_DECLARE(mditop50icons42);
#endif

#if APP_HAVE_MDI_TOP50_FONT_72
LV_FONT_DECLARE(mditop50icons72);
#endif

#if APP_HAVE_MDI_TOP50_FONT_LEGACY
LV_FONT_DECLARE(mditop50icons);
#endif

#elif APP_HAVE_MDI_STANDARD_FONT

LV_FONT_DECLARE(mdi_standard_icons_56);

#endif

#endif


#if APP_HAVE_MDI_WEATHER_FONT_20
LV_FONT_DECLARE(mdiweatherIcons20);
#endif


const lv_font_t *mdi_font_icon_42(void)
{
#if APP_HAVE_MDI_ICON_FONT && \
    APP_HAVE_MDI_TOP50_FONT && \
    APP_HAVE_MDI_TOP50_FONT_42

    return &mditop50icons42;

#else

    return NULL;

#endif
}


bool mdi_font_icon_42_available(void)
{
    return mdi_font_icon_42() != NULL;
}


const lv_font_t *mdi_font_icon_56(void)
{
#if APP_HAVE_MDI_ICON_FONT && \
    APP_HAVE_MDI_TOP50_FONT && \
    APP_HAVE_MDI_TOP50_FONT_56

    return &mditop50icons56;

#elif APP_HAVE_MDI_STANDARD_FONT

    return &mdi_standard_icons_56;

#else

    return NULL;

#endif
}


bool mdi_font_icon_56_available(void)
{
    return mdi_font_icon_56() != NULL;
}


const lv_font_t *mdi_font_icon_72(void)
{
#if APP_HAVE_MDI_ICON_FONT && \
    APP_HAVE_MDI_TOP50_FONT && \
    APP_HAVE_MDI_TOP50_FONT_72

    return &mditop50icons72;

#else

    return NULL;

#endif
}


bool mdi_font_icon_72_available(void)
{
    return mdi_font_icon_72() != NULL;
}


const lv_font_t *mdi_font_large(void)
{
#if APP_HAVE_MDI_ICON_FONT

#if APP_HAVE_MDI_TOP50_FONT

#if APP_HAVE_MDI_TOP50_FONT_56 || \
    APP_HAVE_MDI_STANDARD_FONT

    return mdi_font_icon_56();

#elif APP_HAVE_MDI_TOP50_FONT_72

    return mdi_font_icon_72();

#elif APP_HAVE_MDI_TOP50_FONT_LEGACY

    return &mditop50icons;

#else

    return NULL;

#endif

#elif APP_HAVE_MDI_STANDARD_FONT

    return mdi_font_icon_56();

#else

    return NULL;

#endif

#else

    return NULL;

#endif
}


bool mdi_font_large_available(void)
{
    return mdi_font_large() != NULL;
}


const lv_font_t *mdi_font_weather_20(void)
{
#if APP_HAVE_MDI_WEATHER_FONT_20

    return &mdiweatherIcons20;

#else

    return NULL;

#endif
}


bool mdi_font_weather_20_available(void)
{
    return mdi_font_weather_20() != NULL;
}


const lv_font_t *mdi_font_weather_small(void)
{
#if APP_HAVE_MDI_WEATHER_FONT_20

    return &mdiweatherIcons20;

#endif


#if APP_HAVE_MDI_ICON_FONT && \
    APP_HAVE_MDI_TOP50_FONT

#if APP_HAVE_MDI_TOP50_FONT_42

    return mdi_font_icon_42();

#elif APP_HAVE_MDI_TOP50_FONT_56

    return mdi_font_icon_56();

#elif APP_HAVE_MDI_TOP50_FONT_72

    return mdi_font_icon_72();

#else

    return mdi_font_large();

#endif

#else

    return mdi_font_large();

#endif
}


bool mdi_font_weather_small_available(void)
{
    return mdi_font_weather_small() != NULL;
}


const lv_font_t *mdi_font_weather(void)
{
#if APP_HAVE_MDI_ICON_FONT && \
    APP_HAVE_MDI_TOP50_FONT && \
    APP_HAVE_MDI_TOP50_FONT_72

    return mdi_font_icon_72();

#else

    return mdi_font_large();

#endif
}


bool mdi_font_weather_available(void)
{
    return mdi_font_weather() != NULL;
}


const mdi_icon_entry_t *mdi_icon_registry(
    size_t *out_count)
{
    if (out_count != NULL) {
        *out_count =
            sizeof(s_mdi_icons) /
            sizeof(s_mdi_icons[0]);
    }

    return s_mdi_icons;
}


bool mdi_icon_lookup(
    const char *name,
    uint32_t *out_codepoint)
{
    if (name == NULL ||
        out_codepoint == NULL ||
        name[0] == '\0') {
        return false;
    }

    const size_t count =
        sizeof(s_mdi_icons) /
        sizeof(s_mdi_icons[0]);

    for (size_t i = 0; i < count; ++i) {
        if (strcmp(
                name,
                s_mdi_icons[i].name) == 0) {

            *out_codepoint =
                s_mdi_icons[i].codepoint;

            return true;
        }
    }

    return false;
}


bool mdi_icon_codepoint_to_utf8(
    uint32_t codepoint,
    char out_utf8[5])
{
    if (out_utf8 == NULL ||
        codepoint > 0x10FFFFU ||
        (codepoint >= 0xD800U &&
         codepoint <= 0xDFFFU)) {
        return false;
    }

    if (codepoint <= 0x7FU) {
        out_utf8[0] =
            (char)codepoint;

        out_utf8[1] = '\0';

        return true;
    }

    if (codepoint <= 0x7FFU) {
        out_utf8[0] =
            (char)(
                0xC0U |
                ((codepoint >> 6) & 0x1FU));

        out_utf8[1] =
            (char)(
                0x80U |
                (codepoint & 0x3FU));

        out_utf8[2] = '\0';

        return true;
    }

    if (codepoint <= 0xFFFFU) {
        out_utf8[0] =
            (char)(
                0xE0U |
                ((codepoint >> 12) & 0x0FU));

        out_utf8[1] =
            (char)(
                0x80U |
                ((codepoint >> 6) & 0x3FU));

        out_utf8[2] =
            (char)(
                0x80U |
                (codepoint & 0x3FU));

        out_utf8[3] = '\0';

        return true;
    }

    out_utf8[0] =
        (char)(
            0xF0U |
            ((codepoint >> 18) & 0x07U));

    out_utf8[1] =
        (char)(
            0x80U |
            ((codepoint >> 12) & 0x3FU));

    out_utf8[2] =
        (char)(
            0x80U |
            ((codepoint >> 6) & 0x3FU));

    out_utf8[3] =
        (char)(
            0x80U |
            (codepoint & 0x3FU));

    out_utf8[4] = '\0';

    return true;
}
